### PR TITLE
fix(k8s/broker,k8s/loops.go): update the broker object

### LINKED ISSUE #27: Update broker to pending before calling service class catalog
Then set the broker to available

Ref https://github.com/deis/steward-framework/issues/7

### PR DESCRIPTION
**Pull request by arschles**
Fixes #27 

cc/ @krancour

### CODE REVIEW

File: k8s/broker/update_broker_func.go [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+import (
+	"github.com/deis/steward-framework/k8s/data"
+	"github.com/deis/steward-framework/k8s/restutil"
+	"k8s.io/client-go/rest"
+)
+
+// UpdateBrokerFunc is the function that can update a broker
+type UpdateBrokerFunc func(*data.Broker) (*data.Broker, error)
+
+// NewK8sWatchBrokerFunc returns a WatchBrokerFunc backed by a Kubernetes client
```
Comment (krancour) [inline k8s/broker/update_broker_func.go]: This comment needs to be fixed.

Comment (arschles) [reply k8s/broker/update_broker_func.go]: Fixed in 85ec6e562f2f3256fd2b4d97004c23506ca9c39e
